name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check formatting
        run: npm run prettier:check
      - name: Run Cypress tests
        run: npx cypress run
      - name: Upload Mochawesome Report (with videos)
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: |
            cypress/results/report.html
            cypress/results/videos
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Generate Allure Report
        run: npm run allure:generate
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
